image: node:latest

stages:
    - test
    - pages

test:
    stage: test
    script:
        - npm install --silent
        - npm test

pages:
    stage: pages
    artifacts:
        paths:
            - public
        only:
            - master
