const INIT = 'INIT'
const CREATE_CLIENT_STORE = 'CREATE_CLIENT_STORE'
const CREATE_CLIENT_MANAGER = 'CREATE_CLIENT_MANAGER'
const GET_STATE = 'GET_STATE'

export {
    INIT,
    CREATE_CLIENT_STORE,
    CREATE_CLIENT_MANAGER,
    GET_STATE}
